# Generated by Django 3.1.3 on 2021-06-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('modify_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='Account Youtube URL')),
                ('twitch_url', models.URLField(help_text='Account Twitch URL')),
                ('afreeca_url', models.URLField(help_text='Account AfreecaTV URL')),
                ('namu_url', models.URLField(help_text='Account Namuwiki URL')),
                ('instagram_url', models.URLField(help_text='Account Instagram URL')),
                ('dcinside_url', models.URLField(help_text='Account DC Inside URL')),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='account_on_Sns', to='hoxy.account')),
            ],
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_pic1_url', models.URLField(help_text='Account approving proof picture 1 URL')),
                ('proof_pic2_url', models.URLField(help_text='Account approving proof picture 2 URL')),
                ('proof_vod_url', models.URLField(help_text='Account approving proof video URL')),
                ('proof_pic1_link', models.URLField(help_text='Account approving proof picture 1 link to original')),
                ('proof_pic2_link', models.URLField(help_text='Account approving proof picture 2 link to original')),
                ('proof_vod1_link', models.URLField(help_text='Account approving proof video 1 link to original')),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='account_on_Proof', to='hoxy.account')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Profile Picture URL')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_on_profile', to='hoxy.account')),
            ],
        ),
        migrations.CreateModel(
            name='Nickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Account Nickname', max_length=40)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='account_on_Nickname', to='hoxy.account')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Account Name', max_length=80)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='account_on_Name', to='hoxy.account')),
            ],
        ),
    ]
