# Generated by Django 3.1.3 on 2021-06-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoxy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='proof_pic1_url',
        ),
        migrations.RemoveField(
            model_name='proof',
            name='proof_pic2_url',
        ),
        migrations.RemoveField(
            model_name='proof',
            name='proof_vod_url',
        ),
        migrations.AddField(
            model_name='proof',
            name='proof_pic1',
            field=models.ImageField(help_text='Account approving proof picture 1', null=True, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proof',
            name='proof_pic2',
            field=models.ImageField(help_text='Account approving proof picture 2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proof',
            name='proof_vod',
            field=models.FileField(help_text='Account approving proof video', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(blank=True, help_text='Account Name', max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.ImageField(help_text='Profile Picture URL', upload_to=''),
        ),
        migrations.AlterField(
            model_name='proof',
            name='proof_pic2_link',
            field=models.URLField(help_text='Account approving proof picture 2 link to original', null=True),
        ),
        migrations.AlterField(
            model_name='proof',
            name='proof_vod1_link',
            field=models.URLField(help_text='Account approving proof video 1 link to original', null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='afreeca_url',
            field=models.URLField(help_text='Account AfreecaTV URL', null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='dcinside_url',
            field=models.URLField(help_text='Account DC Inside URL', null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='instagram_url',
            field=models.URLField(help_text='Account Instagram URL', null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='namu_url',
            field=models.URLField(help_text='Account Namuwiki URL', null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='twitch_url',
            field=models.URLField(help_text='Account Twitch URL', null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='youtube_url',
            field=models.URLField(help_text='Account Youtube URL', null=True),
        ),
    ]
