# Generated by Django 3.1.3 on 2021-06-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoxy', '0002_auto_20210616_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.ImageField(help_text='Profile Picture URL', upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='proof_pic1',
            field=models.ImageField(help_text='Account approving proof picture 1', upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='proof_pic2',
            field=models.ImageField(help_text='Account approving proof picture 2', null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='proof_vod',
            field=models.FileField(help_text='Account approving proof video', null=True, upload_to='static/vod/'),
        ),
    ]
