# Generated by Django 3.1.3 on 2021-06-26 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoxy', '0003_auto_20210621_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='account_on_profile', to='hoxy.account'),
        ),
    ]
