# Generated by Django 3.1.3 on 2021-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoxy', '0005_auto_20210626_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.ImageField(help_text='Profile Picture URL', upload_to='img/'),
        ),
    ]
