# Generated by Django 3.1.3 on 2021-07-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoxy', '0007_report_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='proof_pic1',
            field=models.ImageField(help_text='Account approving proof picture 1', upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='proof_pic2',
            field=models.ImageField(help_text='Account approving proof picture 2', null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='proof_vod',
            field=models.FileField(help_text='Account approving proof video', null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='url',
            field=models.ImageField(help_text='Profile Picture URL', upload_to='temp/'),
        ),
    ]
