# Generated by Django 3.2.5 on 2021-07-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoxy', '0008_auto_20210707_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
            ],
        ),
    ]
