# Generated by Django 3.2.5 on 2021-07-08 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False # **<<< HERE**
    initial = True

    dependencies = [
        ('hoxy', '0009_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id',
            new_name='puuid',
        ),
        migrations.RemoveField(
            model_name='name',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='nickname',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='proof',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='sns',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='verify',
            name='account_id',
        ),
        migrations.AddField(
            model_name='name',
            name='puuid',
            field=models.ForeignKey(db_column='puuid', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='account_on_Name', to='hoxy.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nickname',
            name='puuid',
            field=models.ForeignKey(db_column='puuid', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='account_on_Nickname', to='hoxy.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='puuid',
            field=models.ForeignKey(db_column='puuid', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='account_on_Profile', to='hoxy.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proof',
            name='puuid',
            field=models.ForeignKey(db_column='puuid', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_on_Proof', to='hoxy.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sns',
            name='puuid',
            field=models.ForeignKey(db_column='puuid', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_on_Sns', to='hoxy.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verify',
            name='puuid',
            field=models.ForeignKey(db_column='puuid', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_on_Verify', to='hoxy.account'),
            preserve_default=False,
        ),
    ]
