# Generated by Django 3.2.5 on 2021-07-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False # **<<< HERE**
    initial = True

    dependencies = [
        ('hoxy', '0010_auto_20210708_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sns',
            name='puuid',
            field=models.ForeignKey(db_column='puuid', on_delete=django.db.models.deletion.CASCADE, related_name='account_on_SNS', to='hoxy.account'),
        ),
    ]
