# Generated by Django 3.2.5 on 2021-07-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoxy', '0012_alter_account_puuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='puuid',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
