# Generated by Django 3.2.5 on 2021-07-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoxy', '0013_alter_account_puuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nickname',
            name='nickname_search',
            field=models.CharField(default=0, help_text='Account Nickname For Search', max_length=40),
            preserve_default=False,
        ),
    ]
